### PR TITLE
Finishing moving refFunction into core

### PR DESCRIPTION
**Pull request by olivierdalang**
@m-kuhn @enricofer Here's my progress on finishing up the work to get this into a merge-able state (I'm opening this here first for some internal discussion before opening the PR on the main repo)

The feature's really nice :-)

Todo :
- [x] fix tests (there was a crash due to null pointer as QgsFeature doesn't necessarily have a layer, e.g. in tests)
- [x] write function help jsons
- [ ] ~~remove `geometry_overlay_nearest` (we can re-add this once everything else works flawlessly)~~
- [x] cleanup code
- [ ] squash commit history (per author ?)

Questions :

- A. Each function comes in two variants, once as normal and once as `*_test`. The `*_test` version is equivalent to the normal one without any arguments. Can we get rid of the `*_test` ones, or do they serve some purpose ?

- B. I don't like the `geometry_overlay_*` prefix too much (geometry_overlay_disjoint sounds like a contradiction). Can we rename all functions to `spatial_join_*` ? This will also reduce confusion with the plain spatial operators functions (`intersects()...`).

- C. (linked to B.) What about having just one function, and specify the spatial operator as an argument ? This will avoid overcrowding the functions list and better convey that all the functions work on the same principles, and make it easier to add new ones (`intersects_bbox`, ...)

- D. I was a bit surprised at how the sub-expression syntax works (you can just write normally, unquoted expressions, and they are magically evaluated against the other feature). While it's actually quite practical (you get autocomplete), wouldn't it be more clear if this was provided as a string ? This would maybe be more flexible (e.g. for functions like `make_line(...)` where you may want to reference the main feature's context too). Are there other functions that work like this in QGIS ?

### CODE REVIEW

**Comment by enricofer** [comment]
Hi @olivierdalang @m-kuhn, sorry for the late reply, but I can't get the rebased branch compiled, so, for now, I take part to the discussion without having the new function running.
A.
While the non *_test function perform some data extractions with sub expression returning an array of results, the *_test functions returns only a boolean and they arey less computational expensive because they exit as soon as they found a positive and should suffit in many task (for example simbology rules). So I am for keep them, maybe in another syntax.
B.
spatial_join_* sounds good for me too
C.
This point was touched in some previuos discussion and we finally agree to keep them separate to simplify help and take advantage from command autocompletion
D.
I was surprised me too. When I moved from python expression I wasn't aware of this possibility and I found that this feature save the user from the quotes nightmare that otherwise should happen managing subexpressions as strings

I remember that we suspend development because there were some occult issues in attribute tables not revelead by tests. Virtual fields populated by overlay/spatial_join functions were not updated. Could you verify this?

As further todo I suggest to verify if the actual aggregation expression formulas suffit or need dedicated ones first of all a geometry union aggregation function

**Comment by m-kuhn** [comment]
Thanks @olivierdalang and @enricofer 

Most is written already, so I don't have a lot to add.

> D. [...] wouldn't it be more clear if this was provided as a string ? This would maybe be more flexible (e.g. for functions like make_line(...) where you may want to reference the main feature's context too). Are there other functions that work like this in QGIS ?

This is done in other contexts too (e.g. aggregates), so it's a long existing feature we are using. To get access to the main feature, variables are introduced, I would stick to what aggregate does and use `@parent`.

**Comment by enricofer** [comment]
I finally compiled refFunctionRebase branch. 
Everything seem fine but when I test overlay functions in expressions QGIS crashes:

Fatal: ASSERT failure in QList<T>::at: "index out of range", file /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h, line 544
QGIS died on signal -1Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
warning: process 28004 is already traced by process 27999
ptrace: Operazione non permessa.
No thread selected
No stack.
gdb returned 256

I'm on a fresh Ubuntu 20.04 platform and I'm quite sure to have all needed dependencies 
Could someone point me some help?

**Comment by olivierdalang** [comment]
@enricofer 
>I remember that we suspend development because there were some occult issues in attribute tables not revelead by tests. Virtual fields populated by overlay/spatial_join functions were not updated. Could you verify this?

Strange, I tested that yesterday, and had the issue you mentioned (it wouldn't work in the attribute table, both for virtual fields and with the calculator), but today, it works... Not sure what I did differently ?!
Do you remember anything else from the issues you encountered ?

>Everything seem fine but when I test overlay functions in expressions QGIS crashes

Not sure about the crash, let's see what Travis says once we open the PR (here I run the tests on Windows, and have no issues)

>While the non *_test function perform some data extractions with sub expression returning an array of results, the test functions returns only a boolean and they arey less computational expensive because they exit as soon as they found a positive and should suffit in many task (for example simbology rules). So I am for keep them, maybe in another syntax.

I think using the non *_test function without an expression is strictly equivalent that running the *_test functions, no ?
```
  if ( subExpString == "NULL" )
  {
    testOnly = true;
  }
```

**Comment by olivierdalang** [comment]
> > I remember that we suspend development because there were some occult issues in attribute tables not revelead by tests. Virtual fields populated by overlay/spatial_join functions were not updated. Could you verify this?
> 
> Strange, I tested that yesterday, and had the issue you mentioned (it wouldn't work in the attribute table, both for virtual fields and with the calculator), but today, it works... Not sure what I did differently ?!

Now the issue appeared again (seems to happen with gpkgs, but not with memory layers)... For virtual fields, you can still show the labels based on the virtual field, and it works, as if it was only a display issue. But it doesn't with the field calculator.

**Comment by olivierdalang** [comment]
It was just `QgsStaticExpressionFunction()`'s `usesGeometry` parameter that was set to false instead of true...

**Comment by olivierdalang** [comment]
I merged master, so the diff is getting unreadable...
I went ahead and open the PR on the main repo (as a draft for now), let's continue talking there : https://github.com/qgis/QGIS/pull/38405

**Pull request closed without merging**
