### PR TITLE
Trusty

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by m-kuhn** [comment]
@blazek I was experimenting with using the newer ubuntu 14.04 (trusty) instead of ubuntu 12.04 (precise) on travis. Now there seems to be a conflict between grass6 and grass7 when installing. I tried to reproduce the issue locally in a docker container but there it worked. Maybe you have an idea?

https://travis-ci.org/m-kuhn/QGIS/jobs/86026826#L152-L153

**Comment by blazek** [comment]
Maybe they switched to GRASS 7 renaming grass7-dev to grass-dev and there is no more GRASS 6 at all?

**Comment by m-kuhn** [comment]
@blazek This distro has been released April, 2014 and is LTR, I think at that time grass 7 was not released and it would be strange if they'd do such a change in an LTR. Also the package database shows grass 6 for trusty: http://packages.ubuntu.com/trusty/grass

**Comment by blazek** [comment]
No sorry, there are both and briefly looking into contentm, I don't see conflicts in grass-dev and grass-core. It is telling: Depends: grass7-core (= 7.0.1-2~ubuntu14.04.1) but I found only  7.0.1-1 in ubuntugis-unstable and 7.0.2RC1-1 in grass-stable.

And the error: W: Failed to fetch http://ppa.launchpad.net/ubuntugis/ppa/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found ?

**Comment by blazek** [comment]
http://gis.stackexchange.com/questions/129550/ubuntugis-packages-on-ppa-launchpad :
"UbuntuGis was never updated for 14.04." ?

**Pull request closed without merging**
